Vagrant.configure( "2" ) do |config|
    config.vm.provider( "docker" ) do |d|
        d.image = "mtinside/lanager"
        #d.cmd = The lanager Docker image contains a CMD directive, so no need to specify the command to run
        d.ports = [ "12345:80" ]
    end
end
